Use ApplicationSet instead of Application
stolostron/cluster-templates-operator pull request #108
Opened 2023-03-01 17:41 UTC by machacekondra

Day1 implemented

2023-03-01 17:42 UTC, machacekondra commented
@rawagner

2023-04-03 16:24 UTC, rawagner requested changes

2023-04-06 07:47 UTC, rawagner commented
/lgtm

but conflicts need to be resolved :/

2023-04-11 07:43 UTC, rawagner commented
/lgtm

2023-04-11 07:47 UTC, merged