Don't enforce use of quota
stolostron/cluster-templates-operator pull request #110
Opened 2023-03-06 11:21 UTC by machacekondra

If template don't have specified cost, don't enforce quota.

2023-03-06 11:21 UTC, machacekondra commented
@rawagner

2023-04-03 08:34 UTC, rawagner requested changes

2023-04-03 08:34 UTC, rawagner commented on api/v1alpha1/clustertemplateinstance_webhook.go
> +	}
we still need to check for quota presence even if cost is not defined.
```suggestion

```


Instead on line 132 we should have an early return if there is no quota found

2023-04-06 07:42 UTC, rawagner commented
/lgtm

2023-04-06 07:46 UTC, merged