Return only helm with secret helm defined
stolostron/cluster-templates-operator pull request #98
Opened 2023-02-14 12:25 UTC by machacekondra

Signed-off-by: Ondra Machacek <omachace@redhat.com>

2023-02-14 13:26 UTC, rawagner requested changes

2023-02-14 13:26 UTC, rawagner commented on bridge/router.go
> +			repositories = append(repositories, getRepositoryIndex(r.Context(), &secret, cm))
this will cause issues with concurrency. We need to either write only to exact index (as before) or add some guards so only one thread at a time is changing the repositories var.

I'd prefer the index way as that will be easier

2023-02-14 13:26 UTC, rawagner commented on bridge/router.go
> +
We should move this block after the `err` check.
That way we will still be returning `http.StatusNotFound` if the secret is not found (and the test below wont have to change)

2023-02-14 13:53 UTC, machacekondra commented on bridge/router.go
> +			repositories = append(repositories, getRepositoryIndex(r.Context(), &secret, cm))
Done

2023-02-14 13:53 UTC, machacekondra commented on bridge/router.go
> +
Done

2023-02-15 08:08 UTC, rawagner commented
/lgtm

2023-02-15 08:27 UTC, merged